// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCbfyprdYxmLh6RMJc4KG55qY7AfTWy4k',
    appId: '1:193256682433:web:71ecdde98335b88665f540',
    messagingSenderId: '193256682433',
    projectId: 'chat-124f3',
    authDomain: 'chat-124f3.firebaseapp.com',
    storageBucket: 'chat-124f3.firebasestorage.app',
    measurementId: 'G-KK7K2CW773',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9O7LQHDGke0LG-iwAm0rTpmih_cs8meA',
    appId: '1:193256682433:android:a2204e1831774c1065f540',
    messagingSenderId: '193256682433',
    projectId: 'chat-124f3',
    storageBucket: 'chat-124f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHJ0b6GXXgRVeJ9zZ1OIU10ao3e0YvT6Y',
    appId: '1:193256682433:ios:58bb3e1340bf41b165f540',
    messagingSenderId: '193256682433',
    projectId: 'chat-124f3',
    storageBucket: 'chat-124f3.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHJ0b6GXXgRVeJ9zZ1OIU10ao3e0YvT6Y',
    appId: '1:193256682433:ios:58bb3e1340bf41b165f540',
    messagingSenderId: '193256682433',
    projectId: 'chat-124f3',
    storageBucket: 'chat-124f3.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCbfyprdYxmLh6RMJc4KG55qY7AfTWy4k',
    appId: '1:193256682433:web:d5d2a341b2b4bf5065f540',
    messagingSenderId: '193256682433',
    projectId: 'chat-124f3',
    authDomain: 'chat-124f3.firebaseapp.com',
    storageBucket: 'chat-124f3.firebasestorage.app',
    measurementId: 'G-3TRKREMTD0',
  );

}